version: 2
jobs:
  build:
    working_directory: ~/ogp
    machine: true
    steps:
      - checkout
      - run:
          name: "Build Image"
          command: |
            make build
      - run:
          name: "Test"
          command: |
            docker run -d --name agent joshhsoj1902/docker-ogpagent-docker:latest
            sleep 60
            docker ps
            docker exec agent "/docker-health.sh"
