version: '2'
services:
  agent:
    image: joshhsoj1902/docker-ogpagent-docker
    restart: always
    # ports:
    #   - "12679:12679/tcp"
    #   - "27015:27015/tcp"
    #   - "27015:27015/udp"
    # volumes:
    #   - ./ogp_agent/games:/home/ogp_agent/OGP_User_Files
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - OGP_LOGFILE=/opt/OGP/ogp_agent.log
      - OGP_GAME_DIR=/opt/games
      - OGP_LISTEN_PORT=12679
      - OGP_LISTEN_IP=0.0.0.0
      - OGP_VERSION=v3372
      - OGP_KEY=encryption_key2
      - OGP_STEAM_LICENSE=Accept
      - OGP_SUDO_PASSWORD=ogpuser
      - OGP_SCREEN_LOG_LOCAL=1
      - OGP_DELETE_LOGS_AFTER=30
      - OGP_OGP_MANAGES_FTP=1
      - OGP_FTP_METHOD=PureFTPd
      - OGP_AUTORESTART_SERVER=1
      - OGP_DOCKER_NAMESPACE=joshhsoj1902
      - OGP_SWARM_LABEL=games  #TODO: Make this actually do something (it's actually hardcoded)
