defaults: &defaults 
    working_directory: ~/build
    docker: 
      - image: joshhsoj1902/circleci-build-image:1.0.4@sha256:99c3a6a65301dc1fa16bb5bb9b3633f7d7be5470f258943baf466815f66bc51d
remote_docker_version: &remote_docker_version
    version: 17.11.0-ce
version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          <<: *remote_docker_version
      - run:
          name: Prep swarm
          command: |
            docker swarm init 
            docker node update --label-add=game=true $(docker node ls -q)
            docker node update --label-add=games=true $(docker node ls -q) 
      - run:
          name: Build Image
          command: |
            make build
      - run:
          name: Run agent
          background: true
          command: |
            pwd
            #TODO: Rather then leaving this on in the background, we should just add `-d` and pull out all the logs at he end 
            docker-compose up
      - run:
          name: Test
          command: |
            retry -v -s 5 -t 30 'docker-compose exec agent "/docker-health.sh"' #ensure service itself is healthy
            make test
            retry -v -s 5 -t 30 'docker exec $(docker ps -f name=game -q) "./docker-health.sh"'
      - run:
          name: Logs and such
          when: always
          command: |
            docker ps 
            docker service ls

