version: 2
jobs:
  build:
    working_directory: ~/ogp
    machine: true
    steps:
      - checkout
      - run:
          name: "Build Image"
          command: |
            make build
      - run:
          name: "Test"
          command: |
            # docker run -d --name agent joshhsoj1902/docker-ogpagent-docker:latest
            docker-compose -f docker-compose.test.yml up -d
            sleep 60
            docker ps
            docker-compose -f docker-compose.test.yml exec agent "/docker-health.sh"
