defaults: &defaults 
    working_directory: ~/build
    docker: 
      - image: joshhsoj1902/circleci-build-image:latest
remote_docker_version: &remote_docker_version
    version: 17.11.0-ce
version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          <<: *remote_docker_version
      - run:
          name: "Build Image"
          command: |
            make build
      - run:
          name: "Test"
          command: |
            # docker run -d --name agent joshhsoj1902/docker-ogpagent-docker:latest
            docker-compose -f docker-compose.test.yml up -d
            retry -v -s 5 -x 120 -t 1000 'docker-compose -f docker-compose.test.yml exec agent "/docker-health.sh"'
            docker ps
            
