defaults: &defaults 
    working_directory: ~/build
    docker: 
      - image: joshhsoj1902/circleci-build-image:latest
remote_docker_version: &remote_docker_version
    version: 17.11.0-ce
version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          <<: *remote_docker_version
      - run:
          name: Build Image
          command: |
            make build
      - run:
          name: Run agent
          background: true
          command: |
            pwd
            #TODO: Rather then leaving this on in the background, we should just add `-d` and pull out all the logs at he end 
            docker-compose up
      - run:
          name: Test
          command: |
            docker swarm init 
            # docker run -d --name agent joshhsoj1902/docker-ogpagent-docker:latest
            retry -v -s 5 -t 30 'docker-compose exec agent "/docker-health.sh"' #ensure service itself is healthy
            make test
            retry -v -s 5 -t 30 'docker ps && docker exec $(docker ps -f name=game -q) "./docker-health.sh"'

