version: '3.2'
secrets:
  gcloud:
    external: true
services:
  gcloud:
    image: joshhsoj1902/google-cloud-sdk-docker:0.0.2@sha256:9c72ddaf63ad93d7ce4d58683943fdaa7ab700fe026c1eff0c01138c13e25498
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    secrets:
      - gcloud
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.games == true
      restart_policy:
        condition: none
    command: sh -c "gcloud auth activate-service-account --key-file=/run/secrets/gcloud && gcloud docker -- pull {{(datasource "config").namespace}}/{{(datasource "config").image}}:{{(datasource "config").version}}"
    
