version: '3.2'
services:    
  game:
    image: {{(datasource "config").namespace}}/{{(datasource "config").image}}:{{(datasource "config").version}}
    ports:
      - target: {{(datasource "config").port}}
        published: {{(datasource "config").port}}
        protocol: tcp
        mode: host
      - target: {{(datasource "config").port}}
        published: {{(datasource "config").port}}
        protocol: udp
        mode: host
    volumes:
      - "/home/steam/linuxgsm/logs"
      - "/home/steam/linuxgsm/serverfiles/{{(datasource "config").dataVol1}}"
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
      placement:
        constraints:
          - node.labels.games == true
    environment:
      - bind_gateway={{(datasource "bind").bind_gateway}}
      - bind_ingress={{(datasource "bind").bind_ingress}}
      - LGSM_PORT={{(datasource "config").port}}
      - LGSM_MAXPLAYERS={{(datasource "config").maxplayers}}
