version: '3.2'
{{if contains (getenv "STORAGE") "NFS"}}
volumes:
  ogp_{{(datasource "home").homeId}}_storage:
    driver: local
    driver_opts:
      type: nfs
      o: addr={{.Env.STORAGE_NFS_ADDRESS}},rw
      device: ":{{.Env.STORAGE_NFS_PATH}}"
{{end}}
services:    
  game:
    image: {{(datasource "config").namespace}}/{{(datasource "config").image}}:{{(datasource "config").version}}
    ports:
      - target: {{(datasource "config").port}}
        published: {{(datasource "config").port}}
        protocol: tcp
        mode: host
      - target: {{(datasource "config").port}}
        published: {{(datasource "config").port}}
        protocol: udp
        mode: host
    volumes:
      - "/home/steam/linuxgsm/logs"
{{if contains (getenv "STORAGE") "NFS"}}
      - "ogp_{{(datasource "home").homeId}}_storage:/home/steam/linuxgsm/serverfiles/{{(datasource "config").dataVol1}}"
{{else}}
      - "/home/steam/linuxgsm/serverfiles/{{(datasource "config").dataVol1}}"
{{end}}
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
      placement:
        constraints:
          - node.labels.games == true
    environment:
      - bind_gateway={{(datasource "bind").bind_gateway}}
      - bind_ingress={{(datasource "bind").bind_ingress}}
      - LGSM_PORT={{(datasource "config").port}}
      - LGSM_MAXPLAYERS={{(datasource "config").maxplayers}}
